// <auto-generated />
namespace QuotationAppV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class c8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c8));
        
        string IMigrationMetadata.Id
        {
            get { return "201504011644441_c8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
